FROM postgres:10.3-alpine

ARG group_id
ARG user_id

COPY ./healthcheck.sh /

RUN set -x \
    && OLD_UID=$(id -u postgres) \
    && OLD_GID=$(id -g postgres) \
    && deluser postgres \
    && addgroup -g ${group_id} postgres \
    && adduser -D -u ${user_id} -h /var/lib/postgresql -s /bin/sh -G postgres postgres \
    && find / -user ${OLD_UID} -exec chown postgres {} \; \
    && find / -group ${OLD_GID} -exec chgrp postgres {} \; \
    && chmod +x /healthcheck.sh \
    && NPROC=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1) \
    && apk update \
    && apk add --no-cache --virtual .runtimeDeps \
        postgresql-contrib \
#    && psql -U postgres -d ${POSTGRES_DB} -c "CREATE EXTENSION ltree;" \
    && rm -rf /var/cache/apk/* /var/tmp/* /tmp/*