version: "3.5"

services:
  postgres:
    container_name: "${COMPOSE_PROJECT_NAME}_postgres"
    build:
      context: ./containers/postgres
      dockerfile: Dockerfile-alpine
      args:
        - group_id
        - user_id
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "./healthcheck.sh"]
      interval: 3m
      timeout: 10s
      retries: 3
    ports:
      - "5432:5432"
    #volumes:
    #  - ./pgdata:/var/lib/postgresql/data/pgdata:Z
    volumes:
      - ./backup:/var/lib/postgresql/backup:Z
      - pgdata:/var/lib/postgresql/data/pgdata:Z
    networks:
      - web
      - cli
    restart: "no"

  redis-session:
    container_name: "${COMPOSE_PROJECT_NAME}_redis-session"
    build:
      context: ./containers/redis
      dockerfile: Dockerfile-alpine
      args:
        - group_id
        - user_id
    healthcheck:
      test: ["CMD", "./healthcheck.sh"]
      interval: 3m
      timeout: 10s
      retries: 3
    volumes:
      - ./sessions:/data:Z
    #  - ./containers/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    #command: ["CMD", "redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - web
    #logging:
    #  driver: none
    restart: "no"

  memcached:
    container_name: "${COMPOSE_PROJECT_NAME}_memcached"
    build:
      context: ./containers/memcached
      dockerfile: Dockerfile-alpine
    command: ["memcached", "-m", "64m"]
    networks:
      - web
    restart: "no"

  php-fpm:
    container_name: "${COMPOSE_PROJECT_NAME}_php-fpm"
    build:
      context: ./containers/php-fpm
      dockerfile: Dockerfile-alpine
      args:
        - group_id
        - user_id
    networks:
      - web
    volumes:
      - ./app:/var/share:z
      - ./tmp/:/tmp/:z
      - ./var/tmp/:/var/tmp/:z
      - ./containers/php-fpm/conf/php.ini:/usr/local/etc/php/php.ini:ro
    restart: "no"
    #depends_on:
    #  postgres:
    #    condition: service_healthy

  nginx:
    container_name: "${COMPOSE_PROJECT_NAME}_nginx"
    build:
      context: ./containers/nginx
      dockerfile: Dockerfile-alpine
      args:
        - group_id
        - user_id
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - ENV_VAR_LIST=$$NGINX_HOST $$NGINX_PORT $$APP_ENV $$APP_SECRET $$DATABASE_URL
    healthcheck:
      test: ["CMD", "./healthcheck.sh"]
      interval: 3m
      timeout: 10s
      retries: 3
    ports:
      - "80:80"
    volumes:
      - ./app:/var/share:z
      - ./var/log/nginx:/var/log/nginx:Z
      - ./containers/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./containers/nginx/conf/app.conf:/etc/nginx/conf.d/app.conf.tmpl:ro
      - ./containers/nginx/conf/healthcheck.conf:/etc/nginx/conf.d/healthcheck.conf:ro
      - ./containers/nginx/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
    #entrypoint: ["sh", "-c", 'echo "127.0.0.1    meta.local" >> /etc/hosts']
    #entrypoint:
    #  - /bin/sh
    #  - -c
    #  - |
    #       echo "127.0.0.1    ${APP_HOST}" >> /etc/hosts
    #command: /bin/sh -c "echo '127.0.0.1    meta.ru' >> /etc/hosts && nginx -g 'daemon off;'"
    #command: /bin/sh -c "envsubst '$$NGINX_HOST $$NGINX_PORT $$APP_ENV $$APP_SECRET $$DATABASE_URL' < /etc/nginx/conf.d/app.conf.tmpl > /etc/nginx/conf.d/app.conf && exec nginx -g 'daemon off;'"
    networks:
      - web
    restart: "no"
    #depends_on:
    #  php-fpm:
    #    condition: service_healthy

  php-cli:
    container_name: "${COMPOSE_PROJECT_NAME}_php-cli"
    build:
      context: ./containers/php-cli
      dockerfile: Dockerfile-alpine
      args:
        - group_id
        - user_id
    volumes:
      - ./app:/var/share:z
      - ./tmp/:/tmp/:z
      - ./var/tmp/:/var/tmp/:z
      - ./containers/php-cli/conf/php.ini:/usr/local/etc/php/php.ini:ro
    networks:
      - cli
    restart: "no"
    tty: true

  #pgadmin:
  #  container_name: "${COMPOSE_PROJECT_NAME}_pgadmin"
  #  build:
  #    context: ./containers/pgadmin
  #    dockerfile: Dockerfile-alpine
  #    args:
  #      - group_id
  #      - user_id
  #  ports:
  #    - "5050:5050"
  #  volumes:
  #    - ./pgadmin:/pgadmin:Z
  #  networks:
  #    - web
  #  restart: "no"

networks:
  web:
    driver: bridge
  cli:
    driver: bridge

volumes:
  pgdata:
    #external: true
    name: "${COMPOSE_PROJECT_NAME}_pgdata"