#!/usr/bin/env bash

export $(cat ./.env | grep -v ^# | xargs)

docker exec -it "${COMPOSE_PROJECT_NAME}_postgres" sh -c "cd /var/lib/postgresql/backup && pg_dump \${POSTGRES_DB} -U \${POSTGRES_USER} -Fc -T 'logging*' -T 'reversions*' -T 'webhooks_logging*' > dump.gz"