#!/usr/bin/env bash

export $(cat ./.env | grep -v ^# | xargs)

docker exec -it "${COMPOSE_PROJECT_NAME}_postgres" sh -c "cd /var/lib/postgresql/backup && pg_restore -d \${POSTGRES_DB} -U \${POSTGRES_USER} -j 8 dump.gz"