FROM php:7.2-fpm-alpine3.7

ARG group_id
ARG user_id

RUN set -x \
    && deluser www-data \
    && addgroup -g ${group_id} -S www-data \
    && adduser -u ${user_id} -D -S -G www-data www-data \
    && NPROC=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1) \
    && apk update \
    && apk add --no-cache --virtual .buildDeps \
        autoconf \
        g++ \
        gcc \
        libc-dev \
        make \
        re2c \
    && apk add --no-cache --virtual .buildDeps-gd \
        freetype-dev \
        libjpeg-turbo-dev \
        libpng-dev \
        libwebp-dev \
    && apk add --no-cache --virtual .buildDeps-postgres \
        postgresql-dev \
    && apk add --no-cache --virtual .buildDeps-intl \
        icu-dev \
    && apk add --no-cache --virtual .buildDeps-gmagick \
        graphicsmagick-dev \
    && apk add --no-cache --virtual .runtimeDeps-gd \
        freetype \
        libjpeg-turbo \
        libpng \
        libwebp \
    && apk add --no-cache --virtual .runtimeDeps-postgres \
        postgresql \
    && apk add --no-cache --virtual .runtimeDeps-intl \
        icu-libs \
    && apk add --no-cache --virtual .runtimeDeps-gmagick \
        libtool \
        libgomp \
        graphicsmagick \
    && apk add --no-cache --virtual .runtimeDeps-memcached \
        cyrus-sasl-dev \
        libmemcached-dev \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/ --with-webp-dir=/usr/include/ \
    && docker-php-ext-install -j${NPROC} gd pgsql pdo_pgsql intl opcache pcntl \
    && pecl config-set php_ini /usr/local/etc/php/php.ini \
    && pear config-set php_ini /usr/local/etc/php/php.ini \
    && pecl install gmagick-beta \
    && pecl install memcached \
#    && pecl install xdebug \
    && docker-php-ext-enable gmagick \
    && docker-php-ext-enable memcached \
#    && docker-php-ext-enable xdebug \
    && apk del \
        .buildDeps \
        .buildDeps-gd \
        .buildDeps-postgres \
        .buildDeps-intl \
        .buildDeps-gmagick \
    && rm -rf /var/cache/apk/* /var/tmp/* /tmp/* \
    && php -m

USER www-data

#&& update-ca-certificates \

#libtool \
#imagemagick-dev \
#lzip \
#libgomp \
#openssl \
#openssl-dev \
#openssh \
#libcurl \
#libmcrypt-dev \

#buildDeps:
    #autoconf \
    #file \
    #g++ \
    #gcc \
    #libc-dev \
    #make \
    #pkgconf \
    #re2c \

    #curl-dev \
    #libedit-dev \
    #libxml2-dev \
    #openssl-dev \
    #sqlite-dev \

#runtimeDeps:
    #ca-certificates
    #curl
    #tar
    #xz