FROM php:7.2-cli-alpine3.7

ARG group_id
ARG user_id

RUN set -x \
    && deluser www-data \
    && addgroup -g ${group_id} -S www-data \
    && adduser -u ${user_id} -D -S -G www-data www-data \
    && NPROC=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1) \
    && apk update \
    && apk add --no-cache --virtual .buildDeps \
        autoconf \
        g++ \
        gcc \
        libc-dev \
        make \
        re2c \
        wget \
    && apk add --no-cache --virtual .buildDeps-gd \
        freetype-dev \
        libjpeg-turbo-dev \
        libpng-dev \
        libwebp-dev \
    && apk add --no-cache --virtual .buildDeps-postgres \
        postgresql-dev \
    && apk add --no-cache --virtual .buildDeps-intl \
        icu-dev \
    && apk add --no-cache --virtual .buildDeps-gmagick \
        graphicsmagick-dev \
#    && apk add --no-cache --virtual .buildDeps-pthreads \ #zts required
#        pcre-dev \
    && apk add --no-cache --virtual .runtimeDeps \
        git \
        nodejs \
        nodejs-npm \
        yarn \
    && apk add --no-cache --virtual .runtimeDeps-gd \
        freetype \
        libjpeg-turbo \
        libpng \
        libwebp \
    && apk add --no-cache --virtual .runtimeDeps-postgres \
        postgresql \
    && apk add --no-cache --virtual .runtimeDeps-intl \
        icu-libs \
    && apk add --no-cache --virtual .runtimeDeps-gmagick \
        libtool \
        libgomp \
        graphicsmagick \
    && apk add --no-cache --virtual .runtimeDeps-memcached \
        cyrus-sasl-dev \
        libmemcached-dev \
#    && cd / \
#    && git clone https://github.com/krakjoe/pthreads.git \
#    && cd pthreads \
#    && phpize \
#    && ./configure --enable-pthreads \
#    && make -j${NPROC} \
#    && make install \
#    && cd / \
#    && rm -rf pthreads \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/ --with-webp-dir=/usr/include/ \
    && docker-php-ext-install -j${NPROC} gd pgsql pdo_pgsql intl opcache pcntl \
    && pecl config-set php_ini /usr/local/etc/php/php.ini \
    && pear config-set php_ini /usr/local/etc/php/php.ini \
    && pecl install gmagick-beta \
    && pecl install memcached \
#    && pecl install xdebug \
    && docker-php-ext-enable gmagick \
    && docker-php-ext-enable memcached \
#    && docker-php-ext-enable xdebug \
#    && docker-php-ext-enable pthreads \
    && curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer \
#    && composer global require "fxp/composer-asset-plugin:^1.2.0" \
    && wget https://phar.phpunit.de/phpunit.phar \
    && chmod +x phpunit.phar \
    && mv phpunit.phar /usr/local/bin/phpunit \
#    && curl -LsS https://symfony.com/installer -o /usr/local/bin/symfony \
#    && chmod a+x /usr/local/bin/symfony \
    && apk del \
        .buildDeps \
        .buildDeps-gd \
        .buildDeps-postgres \
        .buildDeps-intl \
        .buildDeps-gmagick \
#        .buildDeps-pthreads \
    && rm -rf /var/cache/apk/* /var/tmp/* /tmp/* \
    && php -m

USER www-data

#git \
#libxml2-dev \
#libtool \
#libgomp \
#openssl \
#libmcrypt-dev \
#libcurl \

#buildDeps:
    #autoconf \
    #file \
    #g++ \
    #gcc \
    #libc-dev \
    #make \
    #pkgconf \
    #re2c \

    #curl-dev \
    #libedit-dev \
    #libxml2-dev \
    #openssl-dev \
    #sqlite-dev \

#runtimeDeps:
    #ca-certificates
    #curl
    #tar
    #xz