FROM redis:4.0-alpine

ARG host_group_id
ARG host_user_id

COPY --chown=redis:redis healthcheck.sh /usr/local/bin

RUN set -x \
    && chmod +x /usr/local/bin/healthcheck.sh \
    && ln -s /usr/local/bin/healthcheck.sh /healthcheck.sh \
    && rm -rf /var/cache/apk/* /var/tmp/* /tmp/*
