FROM redis:4.0-alpine

ARG group_id
ARG user_id

COPY ./healthcheck.sh /

RUN set -x \
    && addgroup -g ${group_id} -S www-data \
    && adduser -u ${user_id} -D -S -G www-data www-data \
    && chmod +x /healthcheck.sh

USER www-data