FROM nginx:1.15-alpine

ARG host_group_id
ARG host_user_id

COPY --chown=nginx:nginx healthcheck.sh /usr/local/bin

RUN set -x \
    && addgroup -g ${host_group_id} -S www-data \
    && adduser -u ${host_user_id} -D -S -G www-data www-data \
    && apk update \
    && apk add --no-cache --virtual .runtimeDeps \
        curl \
    && chmod +x /usr/local/bin/healthcheck.sh \
    && ln -s /usr/local/bin/healthcheck.sh /healthcheck.sh \
    && rm -rf /var/cache/apk/* /var/tmp/* /tmp/*

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
