FROM wurstmeister/kafka:2.11-0.10.2.2
#FROM wurstmeister/kafka:2.11-2.0.0

ARG host_group_id
ARG host_user_id

COPY healthcheck.sh /usr/local/bin

RUN set -x \
    && chmod +x /usr/local/bin/healthcheck.sh \
    && ln -s /usr/local/bin/healthcheck.sh /healthcheck.sh \
    && rm -rf /var/cache/apk/* /var/tmp/* /tmp/*
